language: python
sudo: false
python:
  - "2.7"

env:
  global:
    - 'AWS_ACCESS_KEY_ID=AKIAJOOPEXUKZIPG6FIA'
    # AWS_SECRET_ACCESS_KEY
    - secure: "CF2LWIFSNn5OB5Wq7EPUJWasZfqtFZK81vxHux5Eo9vQV6uxnWFBxOx89hdfQ4tfh1bU97SaREF1XnJsreRxGavCLcJzxuLvzvVltHl01kGLMwEOfNrpYLPBjWGuh89G3bxppUn7HRWW8YWqLsF+1ztRc3PypHJ11gAomey/lDvjKYiXevWABOyHflga6sU+NBfrbda/ZuliJnWCVSFavjpUcks/DeN2UUDOzLlnqit19srqkTCDbWTfmwOpC58xC7VU0nVDt6mSXwFlpgVlSt1PHCKHB59eK/eZZ98Q5Rsik62i0kUQMio8q52ibYlem/YUp+BdAq6VsKd2DNhuyRbsijEfgb0IUh4MLmShXCbavmu1V7KqDkliVAw1oO3bHcB5z1JMvVnXxAJIEJitTYSlJXb565mWGvhMZMla/By0HVCFPRqgaAPzE3U0xYuTLpPzvdGeMfmx+6M6kySKt0YVGU6j3yCvRsBAUInauO+x6HGmSpel9ePYxsNd+Yb1r8UF2N2ESVM8P3JZ3qUgtQFkWsbxfkd4+imsFejw/ZriiWjJsnsehOZHSL2KiIO1GofcqJ4KH6zhth8uiY4M+4npjEYq65aUeOqONpQ1i1bKnh22+5x2TlhnMO8w5peu459PmVytGSdb5D+r2jiW+oIecay+OLg7zbA2+MCPIH0="
    - 'CLOUDFRONT_DISTRIBUTION_ID=E1KIBDKGZ4V1S4'
    - 'GOOGLE_ANALYTICS_ID=UA-70495014-1'

install:
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - 'make docs'
  - 'make checkstyle'
  - 'make test'

after_success:
  - ./env/bin/coveralls

notifications:
  email: false
  webhooks:
    urls:
      - secure: "S1WSn6RHODlnu65TsBtPj+9Du3fxNy1Y1AlSOall01ADGn+fMoyBXT8oh0tkF39UKtLnOs7St58Y7r7ow+VrARoN9gM9hd9nkw2e09OnPehqCKXYGFxFqOBDm1Wev+G/O3h4x7V1AYgHQgJgup5dEoFT1aPkXRvtlyHxZFfCJ8bD+2IC4/uZi+WIeydQp6T5vv/v1KXnaoCk9jyBBPTK8g7hkOCvJilPXnpXYKamB2cMmEobodOmd8wjK4dXPRTZcSVbUpMDE1xPzl3pS1j97muDeId2hrfUsafupEyBg08DqGi174sEHV27VtSjCqlA+0+pSgbyLodJy3xb6cFwJFNvJ+WWbuQ2EOsBGuh6loVeXkhirjCLks0vMlsia/NBTraTeyfBHMHItbssS85xPzVwaFSdHPVTuL94g+Fmv7cM5DsffwHDi/iHzSfAOIoj/x85pmydKrBLkuuvbFk8xaw0i52W7/YWYMhjCno9h4qI3C8mCa00O/wq7dbyNBbKVfSKzKXzj/JO3gECSm/ijBQDmiCRnccZGxmC8ZuNVvrxEYuzxBSssPq+s/PZsL3ZGjcBCJ7CAt+yCmy2QV6QIJoussNo6RT8Mn/pJRk88kV/Mj2T3ffR7O7RBitTsUHo6AaQ3C+NlQc2tp87YzMqHgZoOqROH24EEE+n2+tgTsM="
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_deploy:
  - 'make lambda'
  - 'make docs'

deploy:
  - provider: 'releases'
    api_key:
      secure: "SuLg+4btuMDuB4pSuRvKl7QCDNj8AFlGxHacndogBIpmbTFaVlZL+7upyK/F06lXVQz/UrUOh+CoU2FbQ07TbPCxdUej8V2QUIPuk5uaAo+Aszdn/2AoIDQBxbMIcfpc1p8yBe8PN4WcEadpqhUYjS6r6nxecDj1NqIIYv+Gnxsb6q7kfkfugjiRpcylD4byekymgKikC0a8bdongELAohaEAzSyqxi0WsSmsp+/FLQBeMhcW9LbFJ4jbO0hB/fEbvA5+4rH4Nd4wUhUklqVIlrvlVmwbSMmApjrLl/xmmVqt9+sRVg9cJM/ECxiY2g4b5Z1W+NkdltYasPh23TXE0f9iKq0S2Z1VUXPC2/iz8t4UvHrgSnmJXUHFw5r8SaUVj8+hyBZDiECE/a2osLMPhR1vmXfxEHgvfE3SeBq6T0zfnS+OnXUcsKEFmz49jPnOYKwjtGIpHQW/oYCLdKBnr1OWOvCb3oBExhQTqol5Ta9kCBLAOH966gFR7HeztmrPvreNRiz39nUj15qfEMXhxVg5hyOtiLvIRZC/Z80oXHKnqJWDDWNYP4Qrs3Qwc0kpZzBtvBd/n//FZHqo/omO8XrvWfTV1byy7CCLLI1qd8FMxDwWVvW6ZyzRPjxxt6qy4v5d77giY4xM8cVPtLCXz2e8EYNZhZF1t9Y2HKQWH8="
    file: 'lambda.zip'
    skip_cleanup: true
    on:
      repo: 'marvinpinto/irc-hooky'
      tags: true
  - provider: 'script'
    script: 'gem install s3_website && s3_website push --verbose'
    skip_cleanup: true
    on:
      branch: 'master'
      repo: 'marvinpinto/irc-hooky'
